"""Add new tables and fields

Revision ID: 26a591fc2058
Revises: c3b82faa1e22
Create Date: 2024-09-25 15:38:09.739660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a591fc2058'
down_revision = 'c3b82faa1e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_medical_history')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('patient_medical_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('treatment', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='patient_medical_history_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_medical_history_pkey')
    )
    # ### end Alembic commands ###
