from .patient_schema import patient_schema, patients_schema
from .doctor_schema import doctor_schema, doctors_schema
from .appointment_schema import appointment_schema, appointments_schema
from .department_schema import department_schema, departments_schema
from .doctor_department_schema import doctor_department_schema, doctor_departments_schema